### ISSUE TITLE
Image JSON Parsing with ScatterImageView

### ISSUE THREAD

**Issue by sandyjha** [SIMMORSAL/ScatterImageView#1]
I want ,use Image from url as bitmap , does it is possible  , if yes then provide me an example

**Comment by simmorsal** [comment]
You have to have the Bitmap ready before using it in the library. 
Use the tips from following link to get the Bitmap from URL, then pass that to the library:
https://stackoverflow.com/questions/20181491/use-picasso-to-get-a-callback-with-a-bitmap
